INSERT INTO [dbo].[Address] ([IdAddress], [idAddressType], [Address], [IdEmployee]) VALUES (2, 2,N'с. Столбовое, Сакского -на,крымской обл. УССР',1)
INSERT INTO [dbo].[Address] ([IdAddress], [idAddressType], [Address], [IdEmployee]) VALUES (3, 1, N'г. Краснодар, ул. Ставропольская, д.22, корп. Б, кв. 1 ',2)
INSERT INTO [dbo].[Address] ([IdAddress], [idAddressType], [Address], [IdEmployee]) VALUES (4, 2, N'ст.Гривенская, Красноармейский район, Краснодарский Край ',2)
INSERT INTO [dbo].[Address] ([IdAddress], [idAddressType], [Address], [IdEmployee]) VALUES (5, 1, N'г.Краснодар, ул.Волжская, д.4, кв.35 ',3)
INSERT INTO [dbo].[Address] ([IdAddress], [idAddressType], [Address], [IdEmployee]) VALUES (6, 2, N'Кашпир-Рудмий, Куйбышевской области ',3)
INSERT INTO [dbo].[Address] ([IdAddress], [idAddressType], [Address], [IdEmployee]) VALUES (7, 1, N'г. Краснодар, ул.Воронежская д.539, кв.3854 ',4)
INSERT INTO [dbo].[Address] ([IdAddress], [idAddressType], [Address], [IdEmployee]) VALUES (8, 2, N'с. Кучурган, раздельнянского р-на, Одесской области ',4)
INSERT INTO [dbo].[Address] ([IdAddress], [idAddressType], [Address], [IdEmployee]) VALUES (9, 1, N'г. Краснодар, ул.Красная д.58, кв.389 ',5)
INSERT INTO [dbo].[Address] ([IdAddress], [idAddressType], [Address], [IdEmployee]) VALUES (10, 2, N'Кашпир-Рудмий, Куйбышевской области ',5)
INSERT INTO [dbo].[Address] ([IdAddress], [idAddressType], [Address], [IdEmployee]) VALUES (11, 1, N'г. Краснодар, ул. Селезнева, д. 6, кв.14 ',6)
INSERT INTO [dbo].[Address] ([IdAddress], [idAddressType], [Address], [IdEmployee]) VALUES (12, 2,N'с. Кучурган, раздельнянского р-на, Одесской области ',6)
INSERT INTO [dbo].[Address] ([IdAddress], [idAddressType], [Address], [IdEmployee]) VALUES (13, 1, N'г. Краснодар, ул. Ставропольская, д.22, корп. Б, кв. 181 ',7)
INSERT INTO [dbo].[Address] ([IdAddress], [idAddressType], [Address], [IdEmployee]) VALUES (14, 2, N'пос. Пашковский гор. Краснодара ',7)
INSERT INTO [dbo].[Address] ([IdAddress], [idAddressType], [Address], [IdEmployee]) VALUES (15, 1, N'г.Краснодар, ул.Волжская, д.4, кв.63 ',8)
INSERT INTO [dbo].[Address] ([IdAddress], [idAddressType], [Address], [IdEmployee]) VALUES (16, 2, N'гор.Краснодар ',8)
INSERT INTO [dbo].[Address] ([IdAddress], [idAddressType], [Address], [IdEmployee]) VALUES (17, 1, N'г. Краснодар, ул.Воронежская д.539, кв.25 ',9)
INSERT INTO [dbo].[Address] ([IdAddress], [idAddressType], [Address], [IdEmployee]) VALUES (18, 2, N'гор.Краснодар ',9)
INSERT INTO [dbo].[Address] ([IdAddress], [idAddressType], [Address], [IdEmployee]) VALUES (19, 1, N'г. Краснодар, ул.Красная д.58, кв.45 ',10)
INSERT INTO [dbo].[Address] ([IdAddress], [idAddressType], [Address], [IdEmployee]) VALUES (20, 2, N'ст.Гривенская, Красноармейский район, Краснодарский Край ',10)
INSERT INTO [dbo].[Address] ([IdAddress], [idAddressType], [Address], [IdEmployee]) VALUES (21, 1, N'г.Краснодар, ул.Волжская, д.4, кв.34 ',11)
INSERT INTO [dbo].[Address] ([IdAddress], [idAddressType], [Address], [IdEmployee]) VALUES (22, 2, N'Кашпир-Рудмий, Куйбышевской области ',11)
INSERT INTO [dbo].[Address] ([IdAddress], [idAddressType], [Address], [IdEmployee]) VALUES (23, 1, N'г. Краснодар, ул.Воронежская д.539, кв.387 ',12)
INSERT INTO [dbo].[Address] ([IdAddress], [idAddressType], [Address], [IdEmployee]) VALUES (24, 2, N'с. Кучурган, раздельнянского р-на, Одесской области ',12)
INSERT INTO [dbo].[Address] ([IdAddress], [idAddressType], [Address], [IdEmployee]) VALUES (25, 1, N'г. Краснодар, ул.Красная д.58, кв.387 ',13)
INSERT INTO [dbo].[Address] ([IdAddress], [idAddressType], [Address], [IdEmployee]) VALUES (26, 2, N'пос. Пашковский гор. Краснодара ',13)
INSERT INTO [dbo].[Address] ([IdAddress], [idAddressType], [Address], [IdEmployee]) VALUES (27, 1, N'г.Краснодар, ул.Волжская, д.4, кв.3 ',14)
INSERT INTO [dbo].[Address] ([IdAddress], [idAddressType], [Address], [IdEmployee]) VALUES (28, 2, N'гор.Краснодар ',14)
INSERT INTO [dbo].[Address] ([IdAddress], [idAddressType], [Address], [IdEmployee]) VALUES (29, 1,N'г. Краснодар, ул.Воронежская д.539, кв.385 ',15)
INSERT INTO [dbo].[Address] ([IdAddress], [idAddressType], [Address], [IdEmployee]) VALUES (30, 2, N'гор.Краснодар ',15)
INSERT INTO [dbo].[Address] ([IdAddress], [idAddressType], [Address], [IdEmployee]) VALUES (31, 1, N'г. Краснодар, ул.Красная д.58, кв.38 ',16)
INSERT INTO [dbo].[Address] ([IdAddress], [idAddressType], [Address], [IdEmployee]) VALUES (32, 2, N'Кашпир-Рудмий, Куйбышевской области ',16)
INSERT INTO [dbo].[Address] ([IdAddress], [idAddressType], [Address], [IdEmployee]) VALUES (33, 1, N'г. Краснодар, ул. Селезнева, д. 6, кв.12 ',17)
INSERT INTO [dbo].[Address] ([IdAddress], [idAddressType], [Address], [IdEmployee]) VALUES (34, 2, N'с. Кучурган, раздельнянского р-на, Одесской области ',17)
