	INSERT INTO [dbo].[Departments] ([IdDepartment], [DepartmentName], [DepartmentPhoneNumber], [DepartmentHead], [IdEmployee]) VALUES (1, N'Руководство', N'111', 1, 5)
	INSERT INTO [dbo].[Departments] ([IdDepartment], [DepartmentName], [DepartmentPhoneNumber], [DepartmentHead], [IdEmployee]) VALUES (2, N'Административный отдел', N'222', 2, 5)
	INSERT INTO [dbo].[Departments] ([IdDepartment], [DepartmentName], [DepartmentPhoneNumber], [DepartmentHead], [IdEmployee]) VALUES (3, N'Отдел закупок', N'333', 3, 5)
	INSERT INTO [dbo].[Departments] ([IdDepartment], [DepartmentName], [DepartmentPhoneNumber], [DepartmentHead], [IdEmployee]) VALUES (4, N'Отдел продаж', N'444', 4, 5)
	INSERT INTO [dbo].[Departments] ([IdDepartment], [DepartmentName], [DepartmentPhoneNumber], [DepartmentHead], [IdEmployee]) VALUES (5, N'Бухгалтерия', N'555', 5, 5)
	INSERT INTO [dbo].[Departments] ([IdDepartment], [DepartmentName], [DepartmentPhoneNumber], [DepartmentHead], [IdEmployee]) VALUES (6, N'Хозяйственный отдел', N'666', 6, 5)
	INSERT INTO [dbo].[Departments] ([IdDepartment], [DepartmentName], [DepartmentPhoneNumber], [DepartmentHead], [IdEmployee]) VALUES (7, N'Отдел рекламы', N'777', 7, 5)
	INSERT INTO [dbo].[Departments] ([IdDepartment], [DepartmentName], [DepartmentPhoneNumber], [DepartmentHead], [IdEmployee]) VALUES (8, N'Отдел рекламаций', N'888', 8, 5)
	INSERT INTO [dbo].[Departments] ([IdDepartment], [DepartmentName], [DepartmentPhoneNumber], [DepartmentHead], [IdEmployee]) VALUES (9, N'Отдел поддержки пользователей', N'999', 9, 5)
	INSERT INTO [dbo].[Departments] ([IdDepartment], [DepartmentName], [DepartmentPhoneNumber], [DepartmentHead], [IdEmployee]) VALUES (10, N'Транспортный отдел', N'011', 10, 5)
	INSERT INTO [dbo].[Departments] ([IdDepartment], [DepartmentName], [DepartmentPhoneNumber], [DepartmentHead], [IdEmployee]) VALUES (11, N'Отдел кадров', N'012', 11, 5)
	INSERT INTO [dbo].[Departments] ([IdDepartment], [DepartmentName], [DepartmentPhoneNumber], [DepartmentHead], [IdEmployee]) VALUES (12, N'Отдел финансов', N'013', 12, 5)
	INSERT INTO [dbo].[Departments] ([IdDepartment], [DepartmentName], [DepartmentPhoneNumber], [DepartmentHead], [IdEmployee]) VALUES (13, N'Отдел логистики', N'014', 13, 5)
	INSERT INTO [dbo].[Departments] ([IdDepartment], [DepartmentName], [DepartmentPhoneNumber], [DepartmentHead], [IdEmployee]) VALUES (14, N'Отдел ИТ', N'015', 14, 5)
	INSERT INTO [dbo].[Departments] ([IdDepartment], [DepartmentName], [DepartmentPhoneNumber], [DepartmentHead], [IdEmployee]) VALUES (15, N'Отдел развития', N'016', 15, 5)
